### PR TITLE
Add capability of targeting directly maven:package

### PR DESCRIPTION
**Pull request by sonytricoire**
Not sure if properly done but I need to only invoque maven:package and global configuration need to be done.

Because of my doubts I did not update the doc. One simple concern could be the reserved word 'package' that cannot be used in Gruntfile.js to declare the tasks.

### CODE REVIEW

**Comment by smh** [comment]
Thanks, this looks useful. Could you add the documentation, then I'll do the merge. If possible, I would greatly appreciate a unit test for this as well.

I think using package is fine as long as it is quoted, I believe it would only be a problem if used unquoted?

**Comment by sonytricoire** [comment]
Hi,

It works when quoted but actually, 'maven:package' is used in a module
task. I can rename it to mvn:package inside the moduel a expose
maven:package oustide.


2015-11-13 11:55 GMT+01:00 Stein Martin Hustad <notifications@github.com>:

**Comment by sonytricoire** [comment]
It will be better that tests uses the maven_tasks.js getExtension function but I did not manage to do it.
Actually I duplicate the code in tests... :-(

May be you can do it.

**Comment by smh** [comment]
Great, thanks!

**Pull request merged**
