### PR TITLE
fixed async race condition when trying to rename before finishing pac…

### PR DESCRIPTION
**Pull request by bogdanlupuro**
#48

### CODE REVIEW

**Comment by smh** [comment]
Thanks!

**Comment by whansen-git** [comment]
When will this change be made available?  I don't see the changes in master and the last tag cut was 1.3.5 on 11/22/2015.

Thanks,

Bill

**Comment by smh** [comment]
Thanks for reminding me, published version 1.3.6 now.

**Comment by whansen-git** [comment]
Stein,
Thanks for responding.  I see that you published 1.3.6 but it doesn't contain the from pull #49 which fixes the async issue in the section which starts at line 173 (where it registers the task for mvn:package).  I think you had pulled in another fix from someone else which you may have intended to be 1.3.6, not sure about that though.

Thanks,
Bill




| 
 | 
 | 
 | 
 | 
 | 
 | 
 |

**Comment by smh** [comment]
Hmm, looks like I previously closed without merging, not sure how that happened. Anyway, merged now and version 1.3.7 published.

Thank you for your patience!

**Comment by whansen-git** [comment]
Thanks, I see the changes now!

**Pull request merged**
